# Common anchors here
delta_lake_path: &delta_lake_path "output_data_lake" 
# Multiline anchor of executable python code run before a called out function executes. Can be overridden in the actual definition. 
pre_execution_python_code: &pre_execution_python_code | 
  print(results.head(1))
  function_to_execute_arguments["df"] = results
  print(function_to_execute_arguments.keys())
# Array of etl jobs that will be run, each job has an arbitrary number of steps. Valid and invalid examples included. 
etl_jobs: 
  - 
    - step_description: Reading DimLocation Audit Delta Table 
      function_to_execute: read_from_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: DimLocation
        layer: audit
    - step_description: Writing DimLocation to Gold local delta
      function_to_execute: write_to_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: DimLocation
        layer: gold
      pre_execution_python_code: *pre_execution_python_code
  - 
    - step_description: Reading Accounts Audit Delta Table 
      function_to_execute: read_from_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: DimAccounts
        layer: audit
    - step_description: Writing DimAccounts to Gold local delta
      function_to_execute: write_to_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: DimAccounts
        layer: gold
      pre_execution_python_code: *pre_execution_python_code
  - 
    - step_description: Reading DimInventoryItemLocations Audit Delta Table 
      function_to_execute: read_from_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: DimInventoryItemLocations
        layer: audit
    - step_description: Writing DimInventoryItemLocations to Gold local delta
      function_to_execute: write_to_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: DimInventoryItemLocations
        layer: gold
      pre_execution_python_code: *pre_execution_python_code
  - 
    - step_description: Reading DimInventoryItems Audit Delta Table 
      function_to_execute: read_from_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: DimInventoryItems
        layer: audit
    - step_description: Writing DimInventoryItems to Gold local delta
      function_to_execute: write_to_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: DimInventoryItems
        layer: gold
      pre_execution_python_code: *pre_execution_python_code
  - 
    - step_description: Reading FactPurchaseOrder Audit Delta Table 
      function_to_execute: read_from_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: FactPurchaseOrder
        layer: audit
    - step_description: Writing FactPurchaseOrder to Gold local delta
      function_to_execute: write_to_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: FactPurchaseOrder
        layer: gold
      pre_execution_python_code: *pre_execution_python_code
  - 
    - step_description: Reading FactSalesOrder Audit Delta Table 
      function_to_execute: read_from_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: FactSalesOrder
        layer: audit
    - step_description: Writing FactSalesOrder to Gold local delta
      function_to_execute: write_to_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: FactSalesOrder
        layer: gold
      pre_execution_python_code: *pre_execution_python_code
  - 
    - step_description: Reading FactWorkOrder Audit Delta Table 
      function_to_execute: read_from_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: FactWorkOrder
        layer: audit
    - step_description: Writing FactWorkOrder to Gold local delta
      function_to_execute: write_to_local_delta
      function_to_execute_arguments:
        delta_lake_path: *delta_lake_path 
        table_name: FactWorkOrder
        layer: gold
      pre_execution_python_code: *pre_execution_python_code
