SELECT 
   actualShipDate as 'Actual Ship Date'
  ,balance as 'Balance Owed'
  ,billingAddress_id as 'Billing Address ID'
  ,canHaveStackable as 'Are Promotions Stackable?'
  ,ccApproved as 'Credit Card Approved?'
  ,ccAvsStreetMatch as 'Match In Address Verification System for Street?'
  ,ccAvsZipMatch as 'Match In Address Verification System for Zip?' 
  ,ccExpireDate as 'Credit Card Expire Date'
  ,ccName as 'Name On Credit Card'
  ,ccNumber as 'Credit Card Number'
  ,ccSecurityCode as 'Credit Card Security Code'
  ,ccStreet as 'Credit Card Street'
  ,ccZipCode as 'Credit Card Zip Code'
  ,checkNumber as 'Check Number'
  ,createdDate as 'Created Date'
  ,createdFrom_id as 'Created From ID'
  ,currency_id as 'Currency ID'
  ,currencyName as 'Currency Names'
  ,department_id as 'Department ID'
  ,discountRate as 'Discount Rate'
  ,location_id as 'Location ID'
  ,item_id as 'Item ID'
FROM results
