SELECT
   purchaseOrderId as 'Purchase Order ID'
  ,account_id as 'Account ID'
  ,approvalStatus as 'Approval Status'
  ,billAddressList_id as 'Billing Address List ID'
  ,billingAddress as 'Billing Address'
  ,createdDate as 'Created Date'
  ,createdFrom_id as 'Created From ID'
  ,currency_id as 'Currency ID'
  ,currencyName as 'Currency Name'
  ,department_id as 'Department ID'
  ,dueDate as 'Due Date'
  ,email as 'email'
  ,employee_id as 'Employee ID'
  ,exchangeRate as 'Exchange Rate'
  ,location_id as 'Location ID'
  ,memo as 'Memo'
  ,message as 'Message'
  ,orderStatus as 'Order Status'
  ,otherRefNum as 'Order Reference Number'
  ,purchaseContract_id as 'Purchase Contract ID'
  ,shipAddress as 'Shipping Address'
  ,shipDate as 'Ship Date'
  ,shipMethod as 'Ship Method'
FROM results
