SELECT
   workOrderId as 'Work Order ID'
  ,account_id as 'Account ID'
  ,actualProductionEndDate as 'Actual Production End Date'
  ,actualProductionStartDate as 'Actual Production Start Date'
  ,assemblyItem_id as 'Assembly Item ID'
  ,billOfMaterials_id as 'Bill of Materials ID'
  ,billOfMaterialsRevision_id as 'Bill of Materials Revision ID'
  ,buildable as 'Number of Units Buildable'
  ,built as 'Number of Units Built'
  ,createdDate as 'Created Date'
  ,createdFrom_id as 'Created From'
  ,currency_id as 'Currency ID'
  ,currencyName as 'Currency Name'
  ,department_id as 'Department ID'
  ,dueDate as 'Due Date'
  ,email as 'Email'
  ,employee_id as 'Employee ID'
  ,entity_id as 'Entity ID'
  ,workOrderitemListId as 'Work Order Item List'
  ,job_id as 'Job ID'
  ,lastModifiedDate as 'Last Modified Date'
  ,location_id as 'Location ID'
  ,manufacturingRouting_id as 'Manufacturing Routing ID'
  ,memo as 'Memo'
  ,orderStatus as 'Order Status'
  ,quantity as 'Quantity'
  ,requestedDate as 'Requested Date'
  ,revision_id as 'Revision ID'
  ,salesTeamList_id as 'Sales Team List ID'
  ,schedulingMethod as 'Scheduling Method'
  ,startDate as 'Start Date'
  ,status as 'Status'
FROM results
